### ISSUE TITLE
train completed have  not save weight

### ISSUE THREAD

**Issue by lyxbyr** [dingmyu/D4LCN#12]
helllo! i meet problems
train completed, not create weight

**Comment by dingmyu** [comment]
Hi,

The snapshot iter is defined at [here](https://github.com/dingmyu/D4LCN/blob/33d4079b77d14e5c8482abf2b4a636d34c88eafb/scripts/config/depth_guided_config.py#L48).

If it does not work, you may create the `output/` folder, and check the free space of the hard disk。

Thanks
