### ISSUE TITLE
The code of depth-guided module

### ISSUE THREAD

**Issue by gujiaqivadin** [dingmyu/D4LCN#14]
Hello dingmyu!
     Thanks for sharing your gread code! I am interested in your depth-guided module. When I look at your code about this part. I see two adaptive_diated layer. One is between layer2 and layer3, the other is between layer3 and layer4. But I see your paper, the adaptive_diated and dynamic_local_filtering module is after layer3 to prepare for layer4.
      Can you explain why we need 2 such layers in module, and how they work for the whole net.
Thanks a lot!

**Comment by dingmyu** [comment]
Hi,

The depth guidance module is used to integrate depth and spatial information into the backbone network. You can insert this module between any two layers. 

In our experiments, 2-3 such modules are sufficient to meet our model requirements, and even only 1 module can bring significant improvements.

Regards,
Mingyu

**Comment by gujiaqivadin** [comment]
Ok, I got it. Depth-guided module is a fusion module between rgb features and depth features. But I don't know why the shape of weights (the weight between different dilaterate of dynamic_local_filtering ) in module is (-1,512,1,3) and (-1,1024,1,3). Why the resolution is getting bigger while layer adds.

**Comment by dingmyu** [comment]
Hi,

512 and 1024 denote the numbers of channels of block 2 and 3.

Mingyu
