### ISSUE TITLE
your work consumes 0.2s ?what‘s  0.2s contain? 

### ISSUE THREAD

**Issue by kaixinbear** [dingmyu/D4LCN#19]
Hi,dingmyu! I am quite interested in your work, especially its efficiency.But you don't report the run-time in the paper.So I found it on kitti official website.
![image](https://user-images.githubusercontent.com/33575107/80598218-9a15d300-8a5b-11ea-8437-56093f1d39cf.png)
Could you please tell me what does the time represents? Does it including the pre/post-process in the network,such as the time from cpu to gpu ,3D anchor transform, nms, post-optimization ?
Or  just calculating the consuming time of network flow on the gpu,from the processed image to feature map?

**Comment by dingmyu** [comment]
Hi,

It contains the neural network forward time, NMS, and post-optimization, thanks.

We use depth maps, which increases time and improves performance. So time-consuming is not our focus in this paper.

Regards,
Mingyu
