### ISSUE TITLE
Model different to paper

### ISSUE THREAD

**Issue by dannyhung1128** [dingmyu/D4LCN#2]
Hi - thank you for the good work,

I notice that your model in this repo is different from the one you presented in your paper, and that in README you mentioned one can achieve better performance by adding more D4LCN modules. 

Which model is the one you used to produce the results in the paper? What's the difference in terms of performance?

Thanks

**Comment by dingmyu** [comment]
Hi Danny,

What do you mean by the difference between the model and the paper?

The model in this repo is consistent with the paper and can produce the same results as the paper. In the experiment, we found that adding the D4LCN module to the first three blocks achieves the best results. And the D4LCN module after block2 is the most important, the module after block1 is the least important.

For convenience, we try to provide a time-saving model, which can be trained on 11GB GPUs in one day. In README, we provide a simplified version of the model. This model only uses a D4LCN module after block2, which also produces good performance. What we want to prove is that using only one D4LCN module can also bring significant improvements. The result of this simplified model is almost the same as that in the paper, you can download and have a try :)

Thanks

**Comment by dannyhung1128** [comment]
Oops, sorry it seems i was somehow reading your initial commit, not the newest version. I'm sorry :)

**Comment by dannyhung1128** [comment]
just curious, have you switched your depth input into 3d depth, which contains 3d depth points `x, y, z`?

**Comment by dingmyu** [comment]
> The model in this repo is consistent with the paper and can produce the same results as the paper. In the experiment, we found that adding the D4LCN module to the first three blocks achieves the best results. And the D4LCN module after block2 is the most important, the module after block1 is the least important.
> 
> For convenience, we try to provide a time-saving model, which can be trained on 11GB GPUs in one day.

Hi Danny,

As I said, the performance with and without D4LCN on block1 is similar.

Do you mean pseudo-LiDAR representations or x-y-z three channels? I didn't try pseudo-LiDAR because 3D processing should be more time-consuming than 2D. However, using three channels seems like a good idea if u want to try : )

Thanks.

**Comment by dingmyu** [comment]
Feel free to reopen it if you have any further questions.
