### ISSUE TITLE
Executing your model on the KITTI Tracking dataset

### ISSUE THREAD

**Issue by Florijan-Iljazovic** [dingmyu/D4LCN#20]
Hello,

congratulations on phenomenal monocular 3D detection results! (and opensourcing your code)

I have successfully run your pretrained model on Kitti_val1 dataset and results seem great. I was wondering if I could make it work for the Tracking dataset on Kitti as well (http://www.cvlibs.net/datasets/kitti/eval_tracking.php),
 and connect it with some tracker to see how it performs.

So basically I am interested in any advice and intuition you have regarding it - for now it seems to me I should (for evaluation with your pretrained weights):

1. Get DORN depth map results for that dataset
2. Place the dataset and these depth maps somewhere in your project
3. probably change couple of things in your configuration file
4. modify your test.py script

At this point I'm just wondering if I'm missing some other big step in this process before I start ?

**Comment by dingmyu** [comment]
Hi,

Thanks for your attention to my work. Yes, I think these steps are correct.
