### ISSUE TITLE
Dynamic local filtering?

### ISSUE THREAD

**Issue by CVStudent** [dingmyu/D4LCN#21]
Hi,
Very interesting work! I have some problems about dynamic local filtering. 
Line 23 in resnet_dilate.py. In my understanding, shift with different dilation rates (e.g., 1) should only operate on the depth feature. However, in this code, it seems that both the pad_depth and pad_x have the same shift step size. If so, it may be more like direct element-wise product between pad_depth and pad_x. Is there something wrong with my understanding?

Actually, this is a very thoughful idea about depth-guided conv.

**Comment by dingmyu** [comment]
Hi,

Thanks.

1. To achieve local conv, we perform element-wise product before the shift. There maybe some misleads  in our Figure.

2. It should be if not (i==0 and j==0), which means i != 0 or j !=0.

Regards,
Mingyu
