### ISSUE TITLE
Hi, dingmyu, where's Depth-Guided Filtering Module?

### ISSUE THREAD

**Issue by DiegoJohnson** [dingmyu/D4LCN#3]

**Comment by dingmyu** [comment]
Hi, it is in https://github.com/dingmyu/D4LCN/blob/master/models/resnet_dilate.py#L157

Thanks.

**Comment by DiegoJohnson** [comment]
Thanks for your answer, I just begin to read your paper, it's wonderful.
I want to try your model in a new dataset.
1. The original repo of DORN is using caffe which is unfamiliar to me, do you mind to share your DORN model ?

2. Does the depth map have same size as input image(512×1760) ?
![image](https://user-images.githubusercontent.com/43003145/71642764-7203a680-2ceb-11ea-9ead-fa914f9e2eb9.png)

@dingmyu

**Comment by dingmyu** [comment]
Hi Diego,

1. I use the original repo of [DORN](https://github.com/hufu6371/DORN) and the [pretrained model](https://drive.google.com/open?id=180QRn5su1Yf5d-WNqE0jELPNuOpQMjNR) they provided.

It's easy to use and you can follow their instruction to install DORN. You can have a try : ). However, for a new dataset, the depth map extracted by the pre-trained DORN may not be that good. 

2. Yes, they have the same size.

**Comment by DiegoJohnson** [comment]
Thanks very much, I'll have a try.

**Comment by DiegoJohnson** [comment]
sad, one problem after another, I just can't use DORN. 
I use apt install to install caffe-cuda.
then so much errors arise. @dingmyu
