### ISSUE TITLE
Meaning of the Results

### ISSUE THREAD

**Issue by Chenzixi1** [dingmyu/D4LCN#33]
Thanks for your work, I just wonder the meaning of the results:
acc - bg
acc - fg
misc - ry
misc - z
dt

**Comment by polleyr** [comment]
acc - bg = accuracy of background classification
acc - fg = accuracy of foreground object classification
misc - ry = mean angle error
misc - z = mean distance/depth error
dt = average time of an iteration step

**Comment by Chenzixi1** [comment]
> acc - bg = accuracy of background classification acc - fg = accuracy of foreground object classification misc - ry = mean angle error misc - z = mean distance/depth error dt = average time of an iteration step

thans for your response!
