### ISSUE TITLE
result

### ISSUE THREAD

**Issue by yqq924** [dingmyu/D4LCN#34]
excuse me?How to shown the result image?I can just get the result like below
![image](https://user-images.githubusercontent.com/72117934/103886031-d8e84680-511b-11eb-8e96-64c899feb215.png)

**Comment by ruanhailiang** [comment]
Can you share how to display images, Thanks !

**Comment by yqq924** [comment]
use kitti_object_vis tool


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dingmyu/D4LCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 中午1:42
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [dingmyu/D4LCN] result (#34)





 
Can you share how to display images, Thanks !
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
