### ISSUE TITLE
How to get the visual results?

### ISSUE THREAD

**Issue by study-ni** [dingmyu/D4LCN#6]
Hi,
Thanks for your code.
 I don't know how to get the visual results such as :

![000173_proj_new](https://user-images.githubusercontent.com/57343552/71808534-fc138c80-30a8-11ea-974c-e8ba9042a326.png)
Thank you very much for your reply!

**Comment by YuqiHUO** [comment]
Hi, we use  [kitti_object_vis](https://github.com/kuixu/kitti_object_vis) for visualization.
Thank you.

**Comment by dingmyu** [comment]
Feel free to reopen it if you have any further questions.

**Comment by study-ni** [comment]
Hi, I have a question about the results of training. Here is the .txt result from training, such as image_2/002451.txt:
![kk_image](https://user-images.githubusercontent.com/57343552/71882569-aeae2280-316f-11ea-80b6-b31dc15e2a63.jpg)
The first 4 values represent the upper-left and lower-right coordinates of the 2d box, is right?
But the 2d box coordinates in the label are(794.92, 171.12, 870.61, 235.39)(301.59, 184.71, 487.48, 262.98)...
The results are different. I don't know why. Thank you for your reply.
