### ISSUE TITLE
Questions about training results

### ISSUE THREAD

**Issue by study-ni** [dingmyu/D4LCN#7]
Hi, I have a question about the results of training. Here is the .txt result from training, such as image_2/002451.txt:
![kk_image](https://user-images.githubusercontent.com/57343552/71883869-3eed6700-3172-11ea-822c-68e36e308ad5.jpg)
The first 4 values represent the upper-left and lower-right coordinates of the 2d box, is right?
But the 2d box coordinates in the label are(794.92, 171.12, 870.61, 235.39)(301.59, 184.71, 487.48, 262.98)...
The results are different. I don't know why. Thank you for your reply.

**Comment by dingmyu** [comment]
Hi, since the trainval set is split into train and val, we renamed and soft-linked to ensure that the file names are continuous in both train set and val set.

For example, 
```
ls -al data/kitti_split1/validation/label_2/002451.txt

data/kitti_split1/validation/label_2/002451.txt -> YOUR_KITTI_FOLDER/training/label_2/004898.txt
```

In this way, you should check the `data/kitti_split1/validation/label_2` folder rather than `YOUR_KITTI_FOLDER`.

Thanks.
