### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:'/home/rhett.wang/pyProjects/D4LCN/data/kitti_split1/validation/calib/000000.txt'   

### ISSUE THREAD

**Issue by kksgit** [dingmyu/D4LCN#8]
Hi, Mingyu
    I am new on KITTI. I downloaded this database(data_object_image_2 and label_2) and tried train and test on your model. But error appeared: 
FileNotFoundError: [Errno 2] No such file or directory:'/home/rhett.wang/pyProjects/D4LCN/data/kitti_split1/validation/calib/000000.txt'   
   
 I think that it should be my fault on the understanding of KITTI and forgot download something else for training. I failed downloading KITTI from official website because of the WALL!  Then I got it from Baiduyun. The structure of it had been changed. So could you help to tell me which part of KITTI used in your model and the structure of dirctories of KITTI?

**Comment by dingmyu** [comment]
Hi, you should also download the calibration file (data_object_calib.zip) in [Download camera calibration matrices of object data set (16 MB)](http://www.cvlibs.net/download.php?file=data_object_calib.zip), thanks.

KITTI
--training
----image_2, label_2, calib 
--testing
----image_2, label_2, calib

**Comment by kksgit** [comment]
谢啦，终于搞清楚了。求问下有没有第三方链接，我这边亚马逊的那个官方下载链接一直都是没有反应的。。。下载困难户。。

**Comment by kksgit** [comment]
Thanks a lot!

**Comment by dingmyu** [comment]
Thank you.

Feel free to reopen it if you have any further questions.
